spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/eventostec
spring.datasource.username=cauasean
spring.datasource.password=password

# Força o Flyway a rodar
spring.flyway.enabled=true
# Define explicitamente onde procurar (caso você tenha mudado algo)
spring.flyway.locations=classpath:db/migration
# Faz o Hibernate validar se o Flyway criou as tabelas certo
spring.jpa.hibernate.ddl-auto=update

aws.region=us-east-1
aws.bucket.name=eventostec-imagensz