spring.application.name=api
spring.datasource.url=jdbc:postgresql://eventostec-database.cpoae2eoq0q6.us-east-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Sc_z)PD#fF?uRv7]L-*el8BAn3B4

# Hibernate e Dialeto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# AWS
aws.region=us-east-2
aws.bucket.name=eventostec-imagens